#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V
bspc config border_width         2
bspc config window_gap           0
bspc config automatic_scheme spiral
bspc config initial_polarity first_child
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config leaf_monocle

bspc rule -r "*"
bspc rule -a firefox desktop='^2' state="monocle" 
bspc rule -a Chromium desktop='^2' && bspc -layout monocle
bspc rule -a Gcolor2 state=floating rectangle=555x311+0+0
bspc rule -a Spacefm desktop='^5' 
