#!/bin/bash

# #8BB6B6 #98C379

bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc config border_width					2
bspc config focused_border_color			\#C678DD
bspc config normal_border_color				\#616E88

bspc config window_gap           			12

bspc config automatic_scheme 	 			spiral
bspc config initial_polarity 	 			first_child

bspc config focus_follows_pointer			true

bspc config split_ratio          			0.55
bspc config borderless_monocle   			true
bspc config gapless_monocle      			true


##################
## Window rules ##
##################

bspc rule -r "*"

## Workspace 2 (Web browsers)
bspc rule -a firefox desktop='^2' follow=off focus=on
bspc rule -a Chromium desktop='^2' follow=on focus=on

## need to be floating
floating=( VirtualBoxVM Gcolor2 Spacefm Audacious Gparted Preferences dialog menu pop-up task_dialog )

for i in "${floating[@]}"; do
        bspc rule -a $i state=floating follow=on
done
bspc rule -a "VirtualBox Manager" state=floating follow=on

## Load polybar should be last
$XDG_CONFIG_HOME/polybar/launch.sh
