source /home/ka/.config/nvim/myplugs.vim
source /home/ka/.config/nvim/general/keybindings.vim
source /home/ka/.config/nvim/general/options.vim
source /home/ka/.config/nvim/plugconfig/coc/cocbasic.vim
source /home/ka/.config/nvim/plugconfig/coc/explorer.vim
source /home/ka/.config/nvim/plugconfig/lightline.vim
source /home/ka/.config/nvim/plugconfig/easymotion.vim
source /home/ka/.config/nvim/plugconfig/fzf.vim
luafile /home/ka/.config/nvim/plugconfig/colorizer.lua
